name: todo
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  build_runner: ^2.4.15
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.8.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.1.4

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-SemiBold.ttf
  assets:
        - assets/image/Notebook-rafiki.png
        
